# Base16 Black Metal (Khold) theme for Helix
# Adapted from Vim base16-black-metal-khold by metalelf0
# Original by Chris Kempson (http://chriskempson.com)

# Syntax highlighting
"attribute" = "gui0A" # Types, labels (same as Vim Label, Type)
"type" = "gui0A" # Types (same as Vim Type)
"type.builtin" = "gui0A" # Built-in types (same as Vim Type)
"type.parameter" = "gui0A" # Type parameters (same as Vim Type)
"type.enum" = "gui0A" # Enums (same as Vim Type)
"type.enum.variant" = "gui0A" # Enum variants (same as Vim Type)
"constructor" = "gui0D" # Constructors (same as Vim Function)
"constant" = "gui09" # Constants (same as Vim Constant)
"constant.builtin" = "gui09" # Built-in constants (same as Vim Constant)
"constant.builtin.boolean" = "gui09" # Booleans (same as Vim Boolean)
"constant.character" = "gui08" # Characters (same as Vim Character)
"constant.character.escape" = "gui0F" # Escape sequences (same as Vim SpecialChar)
"constant.numeric" = "gui09" # Numbers (same as Vim Number)
"constant.numeric.integer" = "gui09" # Integers (same as Vim Number)
"constant.numeric.float" = "gui09" # Floats (same as Vim Float)
"string" = "gui0B" # Strings (same as Vim String)
"string.regexp" = "gui0C" # Regular expressions (same as Vim jsRegexpString)
"string.special" = "gui0C" # Special strings (same as Vim Special)
"string.special.path" = "gui0D" # Paths (same as Vim Directory)
"string.special.url" = "gui0D" # URLs (same as Vim mailURL)
"string.special.symbol" = "gui0B" # Symbols (same as Vim rubySymbol)
"comment" = "gui03" # Comments (same as Vim Comment)
"comment.line" = "gui03" # Line comments (same as Vim Comment)
"comment.block" = "gui03" # Block comments (same as Vim Comment)
"comment.block.documentation" = "gui03" # Doc comments (same as Vim Comment)
"variable" = "gui08" # Variables (same as Vim Identifier)
"variable.builtin" = "gui08" # Built-in variables (same as Vim Identifier)
"variable.parameter" = "gui08" # Parameters (same as Vim Identifier)
"variable.other" = "gui08" # Other variables (same as Vim Identifier)
"variable.other.member" = "gui08" # Fields (same as Vim Identifier)
"label" = "gui0A" # Labels (same as Vim Label)
"punctuation" = "gui0F" # Punctuation (same as Vim Delimiter)
"punctuation.delimiter" = "gui0F" # Delimiters (same as Vim Delimiter)
"punctuation.bracket" = "gui0F" # Brackets (same as Vim Delimiter)
"punctuation.special" = "gui0F" # Special punctuation (same as Vim Delimiter)
"keyword" = "gui0E" # Keywords (same as Vim Keyword)
"keyword.control" = "gui0E" # Control keywords (same as Vim Conditional)
"keyword.control.conditional" = "gui0E" # Conditionals (same as Vim Conditional)
"keyword.control.repeat" = "gui0E" # Loops (same as Vim Repeat)
"keyword.control.import" = "gui0D" # Imports (same as Vim Include)
"keyword.control.return" = "gui0E" # Return (same as Vim Keyword)
"keyword.control.exception" = "gui08" # Exceptions (same as Vim Exception)
"keyword.operator" = "gui05" # Operators (same as Vim Operator)
"keyword.directive" = "gui0E" # Directives (same as Vim Define)
"keyword.function" = { fg = "gui0E", modifiers = ["italic"] } # Function keywords (same as Vim Keyword)
"keyword.storage" = "gui0A" # Storage classes (same as Vim StorageClass)
"keyword.storage.type" = "gui0A" # Type storage (same as Vim StorageClass)
"keyword.storage.modifier" = "gui0A" # Modifiers (same as Vim StorageClass)
"operator" = "gui05" # Operators (same as Vim Operator)
"function" = "gui0D" # Functions (same as Vim Function)
"function.builtin" = "gui0D" # Built-in functions (same as Vim Function)
"function.method" = "gui0D" # Methods (same as Vim Function)
"function.macro" = "gui0D" # Macros (same as Vim Function)
"function.special" = "gui0D" # Special functions (same as Vim Function)
"tag" = "gui0A" # Tags (same as Vim Tag)
"tag.builtin" = "gui0A" # Built-in tags (same as Vim Tag)
"namespace" = "gui0A" # Namespaces (same as Vim Structure)
"special" = "gui0C" # Special (same as Vim Special)

# Diff highlighting
"diff.plus" = "g" # Added lines (same as Vim DiffAdd, gui0B)
"diff.minus" = "r" # Removed lines (same as Vim DiffDelete, gui08)
"diff.delta" = "g2" # Changed lines (same as Vim DiffChange, gui02)

# UI elements
"ui.background" = { bg = "bg0" } # Main background (same as Vim Normal, gui00)
"ui.cursor" = { fg = "gui00", bg = "gui05" } # Cursor (same as Vim Cursor, gui00/gui05)
"ui.cursor.match" = { bg = "gui03", modifiers = ["bold"] } # Cursor match (same as Vim MatchParen, gui03)
"ui.gutter" = { bg = "bg1" } # Gutter (same as Vim SignColumn, gui01)
"ui.gutter.selected" = { bg = "bg1" } # Selected gutter (same as Vim SignColumn, gui01)
"ui.linenr" = "gui03" # Line numbers (same as Vim LineNr, gui03)
"ui.linenr.selected" = "gui04" # Selected line number (same as Vim CursorLineNr, gui04)
"ui.statusline" = { fg = "gui04", bg = "gui02" } # Status line (same as Vim StatusLine, gui04/gui02)
"ui.statusline.inactive" = { fg = "gui03", bg = "gui01" } # Inactive status line (same as Vim StatusLineNC, gui03/gui01)
"ui.bufferline" = { fg = "gui03", bg = "bg1" } # Buffer line (same as Vim TabLine, gui03/gui01)
"ui.bufferline.active" = { fg = "gui0B", bg = "bg0" } # Active buffer (same as Vim TabLineSel, gui0B/gui01)
"ui.bufferline.background" = { bg = "bg1" } # Buffer line background (same as Vim TabLineFill, gui01)
"ui.popup" = { bg = "bg1" } # Popup menu (same as Vim PMenu, gui01)
"ui.menu" = { fg = "gui05", bg = "bg1" } # Menu (same as Vim PMenu, gui05/gui01)
"ui.menu.selected" = { fg = "gui01", bg = "gui05" } # Selected menu item (same as Vim PMenuSel, gui01/gui05)
"ui.menu.scroll" = { fg = "gui03", bg = "bg1" } # Menu scroll (same as Vim PMenu, gui03/gui01)
"ui.text" = "gui05" # Main text (same as Vim Normal, gui05)
"ui.selection" = { bg = "gui02" } # Text selection (same as Vim Visual, gui02)
"ui.selection.primary" = { bg = "gui02" } # Primary selection (same as Vim Visual, gui02)
"ui.virtual.indent-guide" = "#222222" # Indent guides (same as Vim gui02)
"ui.virtual.inlay-hint" = "gui03" # Inlay hints (same as Vim NonText, gui03)
"ui.virtual.whitespace" = "gui03" # Whitespace (same as Vim NonText, gui03)

# Diagnostics
"warning" = "war" # Warnings (same as Vim WarningMsg, gui09)
"error" = "err" # Errors (same as Vim ErrorMsg, gui08)
"info" = "gui03" # Info (same as Vim NonText, gui03)
"hint" = "gui03" # Hints (same as Vim NonText, gui03)
"diagnostic" = { underline = { style = "dashed" } } # General diagnostics
"diagnostic.error" = { underline = { color = "r", style = "curl" }, modifiers = ["slow_blink"] } # Error diagnostics (same as Vim SpellBad, gui08)
"diagnostic.warning" = { fg = "war", modifiers = ["underline"] } # Warning diagnostics (same as Vim WarningMsg, gui09)
"diagnostic.info" = { fg = "gui03", modifiers = ["underline"] } # Info diagnostics (same as Vim NonText, gui03)
"diagnostic.hint" = { fg = "gui03", modifiers = ["underline"] } # Hint diagnostics (same as Vim NonText, gui03)
"diagnostic.unnecessary" = { modifiers = ["dim"] } # Unnecessary code

[palette]
# GUI colors from Vim theme
gui00 = "#000000" # Black (background)
gui01 = "#121212" # Dark gray (slightly lighter background)
gui02 = "#222222" # Darker gray (selection, visual)
gui03 = "#333333" # Gray (comments, non-text)
gui04 = "#999999" # Light gray (foreground, UI elements)
gui05 = "#c1c1c1" # White (main text)
gui06 = "#999999" # Light gray (unused, same as gui04)
gui07 = "#c1c1c1" # White (unused, same as gui05)
gui08 = "#5f8787" # Teal (errors, identifiers)
gui09 = "#aaaaaa" # Light gray (constants, numbers)
gui0A = "#974b46" # Reddish (labels, types)
gui0B = "#eceee3" # Light gray-green (strings, added diff)
gui0C = "#aaaaaa" # Light gray (special, unused)
gui0D = "#888888" # Gray (functions, directories)
gui0E = "#999999" # Light gray (keywords, conditionals)
gui0F = "#444444" # Dark gray (delimiters, special chars)

# Additional colors for Helix-specific needs
r = "#5f8787" # Teal (errors, same as gui08)
g = "#eceee3" # Light gray-green (added diff, same as gui0B)
b = "#888888" # Gray (functions, same as gui0D)
err = "#5f8787" # Teal (errors, same as gui08)
war = "#aaaaaa" # Light gray (warnings, same as gui09)
bg0 = "#000000" # Black (background, same as gui00)
bg1 = "#121212" # Dark gray (UI backgrounds, same as gui01)
g5 = "#c1c1c1" # White (main text, same as gui05)
g4 = "#999999" # Light gray (foreground, same as gui04)
g3 = "#333333" # Gray (comments, same as gui03)
g2 = "#222222" # Darker gray (diff delta, same as gui02)
g1 = "#121212" # Dark gray (UI backgrounds, same as gui01)
